services:
  webserver:
    restart: unless-stopped
    build:
      context: ./src
      dockerfile: ./Dockerfile
      target: production
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    expose:
      - "8080"

